on: [push]

name: test

jobs:
  check:
    env:
      RPC_1: $RPC_1
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: false

      - name: Run tests
        run: forge test -vvv

      - name: Check formatting
        run: forge fmt --check
