on: [push]
env:
  RPC_1: ${{ vars.RPC_1 }}
  FOUNDRY_FUZZ_SEED: 0x1c6b15adc6fa0c1144b8dce3443a90c59bbd566170363d66768a038d09a06e23

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: false

      - name: Run tests
        run: forge test -vvv

      - name: Check formatting
        run: forge fmt --check
